language: go

go:
  - 1.8
  - 1.9
  - 1.10

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify
  - go test -v -covermode=atomic -coverprofile=coverage.txt

after_success:
- bash <(curl -s https://codecov.io/bash)
